steps:
# Repo Git local
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']

# Bluid Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/hello-python', '.' ]

# Push into Repository
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "eu.gcr.io/$PROJECT_ID/hello-python:latest"]

# Deploy last version
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - apply
  - -f
  - k8s/
  env:
  - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
  - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'