apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hello-python
  labels:
    app: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: eu.gcr.io/cflmm-proxyapi/hello-python:latest
        ports:
        - containerPort: 8080
